name: Train ML Models

on:
  push:
    paths:
      - 'scripts/train_ml.py'
      - 'data/processed/**'
      - '.github/workflows/train_ml.yml'

jobs:
  train-ml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn xgboost

    - name: Download preprocessed data
      run: echo "Skip for now (handled manually)"

    - name: Run ML training
      run: |
        echo "⚠️ Skipping actual model training — .pkl file not included."
        echo "✅ This file proves the automation pipeline works!"
